import type { AnalysisResult } from '@/lib/api/types'

export const SHARE_CARD_WIDTH = 1080
export const SHARE_CARD_HEIGHT = 1920
const MARGIN = 96

export interface ShareCardLabels {
  days: string
  messages: string
  /** Already pluralized, e.g. "3 episodios de conflicto" is built as value + label */
  conflict: string
  /** Label shown under the turning point date */
  turning: string
}

export interface ShareCardRow {
  value: string
  label: string
}

export interface ShareCardData {
  days: number
  daysLabel: string
  rows: ShareCardRow[]
  host: string
}

type FullResult = NonNullable<AnalysisResult['result']>

// "2026-09-14", "2026-09" or "2026-Q3" -> readable text in the given locale
function formatPeriod(period: string, locale: string): string {
  const daily = period.match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (daily) {
    const d = new Date(Number(daily[1]), Number(daily[2]) - 1, Number(daily[3]))
    return d.toLocaleDateString(locale, { day: 'numeric', month: 'long', year: 'numeric' })
  }
  const monthly = period.match(/^(\d{4})-(\d{2})$/)
  if (monthly) {
    const d = new Date(Number(monthly[1]), Number(monthly[2]) - 1, 1)
    return d.toLocaleDateString(locale, { month: 'long', year: 'numeric' })
  }
  const quarterly = period.match(/^(\d{4})-Q(\d)$/)
  if (quarterly) return `Q${quarterly[2]} ${quarterly[1]}`
  return period
}

/** Pure: builds the card content from a full result. Contains no names or message text. */
export function buildShareCardData(
  result: FullResult,
  locale: string,
  labels: ShareCardLabels,
  host = '',
): ShareCardData {
  const fmt = new Intl.NumberFormat(locale)
  const overview = result.temporal.overview
  const rows: ShareCardRow[] = []

  if (overview.total_messages > 0) {
    rows.push({ value: fmt.format(overview.total_messages), label: labels.messages })
  }

  const conflict = result.conflict
  const episodes = conflict && !('error' in conflict) ? conflict.episodes.length : 0
  if (episodes > 0) {
    rows.push({ value: fmt.format(episodes), label: labels.conflict })
  }

  const turning = result.temporal.response_decay?.turning_point
  if (turning) {
    rows.push({ value: formatPeriod(turning, locale), label: labels.turning })
  }

  return {
    days: overview.date_range.total_days,
    daysLabel: labels.days,
    rows,
    host,
  }
}

function cssVar(name: string, fallback: string): string {
  const v = getComputedStyle(document.documentElement).getPropertyValue(name).trim()
  return v || fallback
}

/** Resolves the real font-family strings generated by next/font from live elements. */
export function resolveFonts(): { mono: string; serif: string } {
  const mono = getComputedStyle(document.body).fontFamily
  const probe = document.createElement('span')
  probe.style.fontFamily = 'var(--font-instrument-serif), "Instrument Serif", serif'
  probe.style.position = 'absolute'
  probe.style.visibility = 'hidden'
  document.body.appendChild(probe)
  const serif = getComputedStyle(probe).fontFamily
  probe.remove()
  return { mono, serif }
}

/** Waits until the card fonts are ready to be used by the canvas. */
export async function loadShareFonts(): Promise<void> {
  const { mono, serif } = resolveFonts()
  await document.fonts.ready
  await Promise.all([
    document.fonts.load(`400 100px ${serif}`),
    document.fonts.load(`400 36px ${mono}`),
  ]).catch(() => undefined)
}

export function renderShareCard(canvas: HTMLCanvasElement, data: ShareCardData): void {
  canvas.width = SHARE_CARD_WIDTH
  canvas.height = SHARE_CARD_HEIGHT
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  const { mono, serif } = resolveFonts()
  const background = cssVar('--background', '#0a0a0a')
  const primary = cssVar('--text-primary', '#f0f0f0')
  const muted = cssVar('--text-muted', '#888888')
  const warm = cssVar('--warm', '#c8a27a')

  ctx.fillStyle = background
  ctx.fillRect(0, 0, SHARE_CARD_WIDTH, SHARE_CARD_HEIGHT)
  ctx.textAlign = 'left'
  ctx.textBaseline = 'alphabetic'

  // Brand
  ctx.fillStyle = muted
  ctx.font = `400 34px ${mono}`
  if ('letterSpacing' in ctx) (ctx as unknown as { letterSpacing: string }).letterSpacing = '8px'
  ctx.fillText('LASTSEEN', MARGIN, 168)
  if ('letterSpacing' in ctx) (ctx as unknown as { letterSpacing: string }).letterSpacing = '0px'

  // Main figure: size shrinks if the number is wide
  const daysText = String(data.days)
  let size = 440
  ctx.font = `400 ${size}px ${serif}`
  const maxWidth = SHARE_CARD_WIDTH - MARGIN * 2
  while (ctx.measureText(daysText).width > maxWidth && size > 120) {
    size -= 20
    ctx.font = `400 ${size}px ${serif}`
  }
  ctx.fillStyle = warm
  ctx.fillText(daysText, MARGIN, 700)

  ctx.fillStyle = muted
  ctx.font = `400 44px ${mono}`
  ctx.fillText(data.daysLabel, MARGIN, 780)

  // Data rows
  const rowHeight = 200
  let y = 1100
  for (const row of data.rows.slice(0, 3)) {
    ctx.fillStyle = primary
    ctx.font = `400 96px ${serif}`
    ctx.fillText(row.value, MARGIN, y)
    ctx.fillStyle = muted
    ctx.font = `400 36px ${mono}`
    ctx.fillText(row.label, MARGIN, y + 56)
    y += rowHeight
  }

  // Site address
  ctx.fillStyle = muted
  ctx.font = `400 32px ${mono}`
  ctx.fillText(data.host, MARGIN, SHARE_CARD_HEIGHT - 110)
}
